import type { Inventory, Product } from "@/lib/shared/types";

const brands = {
  headphones: ["Auralis", "Soundform", "EchoPeak"],
  laptops: ["Northbyte", "VoltBook", "CedarOS"],
  chairs: ["Sitwell", "ErgoLane", "FormSeat"],
  cameras: ["Lumen", "FrameKit", "Aperture"],
} as const;

function product(
  id: string,
  name: string,
  category: string,
  brand: string,
  price: number,
  specs: Record<string, string>,
  description: string,
): Product {
  return {
    id,
    name,
    category,
    brand,
    price,
    specs,
    imageKey: category,
    description,
  };
}

export const SEED_PRODUCTS: Product[] = [
  product(
    "hp-01",
    "Auralis Pulse ANC",
    "headphones",
    brands.headphones[0],
    249,
    { battery: "40h", weight: "250g", anc: "hybrid", driver: "40mm", wireless: "yes" },
    "Over-ear ANC headphones with long battery life and balanced tuning.",
  ),
  product(
    "hp-02",
    "Soundform Drift",
    "headphones",
    brands.headphones[1],
    179,
    { battery: "30h", weight: "220g", anc: "hybrid", driver: "40mm", wireless: "yes" },
    "Lightweight travel headphones with solid noise cancellation.",
  ),
  product(
    "hp-03",
    "EchoPeak Studio Pro",
    "headphones",
    brands.headphones[2],
    329,
    { battery: "45h", weight: "280g", anc: "adaptive", driver: "50mm", wireless: "yes" },
    "Studio-leaning headphones for critical listening and calls.",
  ),
  product(
    "hp-04",
    "Auralis Commute Mini",
    "headphones",
    brands.headphones[0],
    129,
    { battery: "24h", weight: "180g", anc: "basic", driver: "32mm", wireless: "yes" },
    "Compact on-ear model for daily commuting.",
  ),
  product(
    "hp-05",
    "Soundform OpenAir",
    "headphones",
    brands.headphones[1],
    149,
    { battery: "18h", weight: "160g", anc: "none", driver: "open", wireless: "yes" },
    "Open-ear design for awareness while walking or cycling.",
  ),
  product(
    "hp-06",
    "EchoPeak Wire Reference",
    "headphones",
    brands.headphones[2],
    199,
    { battery: "n/a", weight: "300g", anc: "none", driver: "50mm", wireless: "no" },
    "Wired reference headphones for desk mixing.",
  ),
  product(
    "lp-01",
    "Northbyte Air 14",
    "laptops",
    brands.laptops[0],
    1199,
    { cpu: "N14", ram: "16GB", storage: "512GB", display: "14\" 120Hz", weight: "1.2kg" },
    "Thin productivity laptop with long battery endurance.",
  ),
  product(
    "lp-02",
    "VoltBook Creator 15",
    "laptops",
    brands.laptops[1],
    1599,
    { cpu: "V15", ram: "32GB", storage: "1TB", display: "15\" OLED", weight: "1.6kg" },
    "Creator-focused machine with a bright OLED panel.",
  ),
  product(
    "lp-03",
    "CedarOS Field 13",
    "laptops",
    brands.laptops[2],
    999,
    { cpu: "C13", ram: "16GB", storage: "512GB", display: "13\" 60Hz", weight: "1.1kg" },
    "Compact ultraportable for travel writing and coding.",
  ),
  product(
    "lp-04",
    "Northbyte ProDock 16",
    "laptops",
    brands.laptops[0],
    1899,
    { cpu: "N16", ram: "32GB", storage: "1TB", display: "16\" 165Hz", weight: "1.9kg" },
    "Performance laptop with a high-refresh display.",
  ),
  product(
    "lp-05",
    "VoltBook Slim 14",
    "laptops",
    brands.laptops[1],
    1099,
    { cpu: "V14", ram: "16GB", storage: "512GB", display: "14\" 90Hz", weight: "1.3kg" },
    "Balanced everyday laptop for office work.",
  ),
  product(
    "lp-06",
    "CedarOS Studio 15",
    "laptops",
    brands.laptops[2],
    1749,
    { cpu: "C15", ram: "32GB", storage: "2TB", display: "15\" miniLED", weight: "1.7kg" },
    "Studio laptop with color-accurate miniLED display.",
  ),
  product(
    "lp-07",
    "Northbyte Budget 15",
    "laptops",
    brands.laptops[0],
    749,
    { cpu: "N10", ram: "8GB", storage: "256GB", display: "15\" 60Hz", weight: "1.8kg" },
    "Affordable laptop for browsing and documents.",
  ),
  product(
    "ch-01",
    "Sitwell Focus Mesh",
    "chairs",
    brands.chairs[0],
    449,
    { material: "mesh", recline: "120°", lumbar: "adjustable", arms: "4D", weightCapacity: "120kg" },
    "Breathable mesh task chair with adjustable lumbar support.",
  ),
  product(
    "ch-02",
    "ErgoLane Apex",
    "chairs",
    brands.chairs[1],
    599,
    { material: "mesh", recline: "135°", lumbar: "dynamic", arms: "4D", weightCapacity: "135kg" },
    "Premium ergonomic chair for long coding sessions.",
  ),
  product(
    "ch-03",
    "FormSeat Craft Leather",
    "chairs",
    brands.chairs[2],
    699,
    { material: "leather", recline: "125°", lumbar: "adjustable", arms: "3D", weightCapacity: "125kg" },
    "Leather executive chair with a refined silhouette.",
  ),
  product(
    "ch-04",
    "Sitwell Compact",
    "chairs",
    brands.chairs[0],
    299,
    { material: "fabric", recline: "110°", lumbar: "fixed", arms: "fixed", weightCapacity: "110kg" },
    "Compact chair for small home offices.",
  ),
  product(
    "ch-05",
    "ErgoLane Draft",
    "chairs",
    brands.chairs[1],
    379,
    { material: "mesh", recline: "115°", lumbar: "adjustable", arms: "2D", weightCapacity: "115kg" },
    "Drafting-height stool with foot ring and mesh back.",
  ),
  product(
    "ch-06",
    "FormSeat Guest Pair",
    "chairs",
    brands.chairs[2],
    249,
    { material: "fabric", recline: "none", lumbar: "none", arms: "none", weightCapacity: "100kg" },
    "Stackable guest chairs sold as a pair.",
  ),
  product(
    "ch-07",
    "Sitwell Night Shift",
    "chairs",
    brands.chairs[0],
    529,
    { material: "mesh", recline: "130°", lumbar: "dynamic", arms: "4D", weightCapacity: "130kg" },
    "Night-shift ready chair with extended recline.",
  ),
  product(
    "cam-01",
    "Lumen Pocket X",
    "cameras",
    brands.cameras[0],
    899,
    { sensor: "1\"", megapixels: "20", zoom: "3x", video: "4K60", weather: "no" },
    "Pocket camera with strong stills and video flexibility.",
  ),
  product(
    "cam-02",
    "FrameKit Mirrorless A",
    "cameras",
    brands.cameras[1],
    1299,
    { sensor: "APS-C", megapixels: "26", zoom: "lens-dependent", video: "4K30", weather: "yes" },
    "APS-C mirrorless body for travel photography.",
  ),
  product(
    "cam-03",
    "Aperture Fullframe One",
    "cameras",
    brands.cameras[2],
    2199,
    { sensor: "full-frame", megapixels: "45", zoom: "lens-dependent", video: "6K", weather: "yes" },
    "Full-frame body aimed at hybrid photo and video work.",
  ),
  product(
    "cam-04",
    "Lumen Action Seal",
    "cameras",
    brands.cameras[0],
    349,
    { sensor: "1/1.7\"", megapixels: "12", zoom: "fixed", video: "5.3K", weather: "waterproof" },
    "Rugged action camera for outdoor sports.",
  ),
  product(
    "cam-05",
    "FrameKit Compact Z",
    "cameras",
    brands.cameras[1],
    749,
    { sensor: "1\"", megapixels: "20", zoom: "5x", video: "4K30", weather: "no" },
    "Travel zoom compact with a versatile lens.",
  ),
  product(
    "cam-06",
    "Aperture Cinema Mini",
    "cameras",
    brands.cameras[2],
    1599,
    { sensor: "Super35", megapixels: "6K", zoom: "lens-dependent", video: "6K", weather: "yes" },
    "Compact cinema camera for indie productions.",
  ),
  product(
    "hp-07",
    "Auralis Desk Duo",
    "headphones",
    brands.headphones[0],
    99,
    { battery: "n/a", weight: "210g", anc: "none", driver: "40mm", wireless: "no" },
    "Affordable wired desk headphones.",
  ),
  product(
    "lp-08",
    "VoltBook Rugged 14",
    "laptops",
    brands.laptops[1],
    1399,
    { cpu: "V14R", ram: "16GB", storage: "1TB", display: "14\" 120Hz", weight: "1.5kg" },
    "Spill-resistant laptop for field engineering.",
  ),
  product(
    "ch-08",
    "FormSeat Lounge",
    "chairs",
    brands.chairs[2],
    799,
    { material: "leather", recline: "140°", lumbar: "adjustable", arms: "fixed", weightCapacity: "140kg" },
    "Lounge chair for reading and light work.",
  ),
  product(
    "cam-07",
    "Lumen Instant Print",
    "cameras",
    brands.cameras[0],
    149,
    { sensor: "instant", megapixels: "n/a", zoom: "fixed", video: "none", weather: "no" },
    "Instant print camera for events and parties.",
  ),
];

export const SEED_INVENTORY: Inventory[] = SEED_PRODUCTS.map((p, i) => ({
  productId: p.id,
  stock: i % 7 === 0 ? 0 : 5 + (i % 20),
  warehouse: i % 2 === 0 ? "west" : "east",
  restockAt: i % 7 === 0 ? Date.now() + 3 * 24 * 60 * 60 * 1000 : undefined,
}));

export const PRODUCT_FIELD_WHITELIST = [
  "id",
  "name",
  "category",
  "brand",
  "price",
  "description",
  "specs.battery",
  "specs.weight",
  "specs.anc",
  "specs.driver",
  "specs.wireless",
  "specs.cpu",
  "specs.ram",
  "specs.storage",
  "specs.display",
  "specs.material",
  "specs.recline",
  "specs.lumbar",
  "specs.arms",
  "specs.weightCapacity",
  "specs.sensor",
  "specs.megapixels",
  "specs.zoom",
  "specs.video",
  "specs.weather",
] as const;
